[info]
bundles = ["Zinnia.dylib", "ZinniaPrefs"]
ctor = true

[protection]
anti-debug = true
dpkg-check = true
encryption = true
faro-shuffle = true
garbage-asm = true

[targets.arm64]
arch = "arm64"
target = "arm64-apple-ios"
sysroot = "/Users/aspen/Library/Theos/sdks/iPhoneOS14.4.sdk"

[targets.arm64e]
arch = "arm64e"
target = "arm64e-apple-ios"
sysroot = "/Users/aspen/Library/Theos/sdks/iPhoneOS14.4.sdk"

[dpkg]
bad = [
	"/var/lib/dpkg/info/org.mr.zinnia.list",
	"/var/lib/dpkg/info/ru.rejail.zinnia.list",
	"/var/lib/dpkg/info/ru.rj.zinnia.list",
	"/var/lib/dpkg/info/org.hackyouriphone.zinnia.list",
]
good = [
	"/var/lib/dpkg/info/me.aspenuwu.zinnia.list",
	"/var/lib/dpkg/info/me.aspenuwu.zinnia.trial.list",
]

[sections]
strtab = "__DATA,__brimstonestrtb"
strtab-toc = "__DATA,__brimstonetoc"
strtab-keys = "__TEXT,__brimstonedk"
jmp = "__TEXT,__brimstonecrc"
jmp-key = "__TEXT,__brimstonehka"
code-key = "__TEXT,__brimstonekay"
code-decrypt = "__TEXT,__brimstoneldr"
dpkg-hash = "__TEXT,__brimstoneapk"
