[package]
name = "checksuminator"
version = "0.1.0"
authors = ["aspen <aspenuwu@protonmail.com>"]
edition = "2018"

[dependencies]
blake3 = "0.3.7"
bytemuck = { version = "1.5.1", features = ["derive"] }
chacha20 = "0.6.0"
goblin = "0.4.0"
rand = "0.8.3"
structopt = "0.3.21"
