#pragma once

#define TWEAK_DYLIB "Zinnia.dylib"
#define PREFS_BUNDLE "ZinniaPrefs"

//////////////////////////
// String Table-related //
//////////////////////////

/// The section used for the encrypted table of contents of the string table.
#define SECTION_STRING_TABLE_OF_CONTENTS "__DATA,__aiwasstoc"
/// The section used for the encrypted string table.
#define SECTION_STRING_TABLE "__DATA,__aiwassstrtb"
/// The section used for the keypairs used to enecrypt the string table sections
#define SECTION_STRING_TABLE_KEYS "__TEXT,__aiwassdk"

///////////////////////
// Integrity-related //
///////////////////////

/// The section containing the checksums of various functions and sections
#define SECTION_CHECKSUM_LOOKUP_TABLE "__TEXT,__aiwasscrc"
/// The section containing the key used to initialize the hasher used for
/// calculating the checksums of functions and sections.
#define SECTION_CHECKSUM_HASH_KEY "__TEXT,__aiwasshka"

/////////////////////////
// Obfuscation-related //
/////////////////////////

/// If this is enabled, then many different structures will be obfuscated by a
/// Faro Shuffle (https://en.wikipedia.org/wiki/Faro_shuffle), adding difficulty
/// to the process of static analysis.
#define USE_PERFECT_SHUFFLING

/// The section containing the key used to decrypt the main (__TEXT,__text) section
#define SECTION_CODE_DECRYPTION_KEY "__TEXT,__aiwasskay"
/// This section contains the function that will decrypt __TEXT,__Text
#define SECTION_CODE_DECRYPTION_ROUTINE "__TEXT,__aiwassldr"

#define ANTI_DEBUG

//////////////////////////////
// Direct anti-piracy stuff //
//////////////////////////////

/// The section containing the key used to initialize the hasher
/// used for detecting pirated package filenames.
#define SECTION_FILENAME_HASH_KEY "__TEXT,__aiwassapk"
/// The path to the "correct" dpkg .list file
#define GOOD_FILENAME "/var/lib/dpkg/info/me.aspenuwu.zinnia.list"
/// The hash of the path of the "correct" dpkg .list file
/// This define will be automatically generated by the preprocessor, only edit the GOOD_FILENAME define!
#pragma blake3 SECTION_FILENAME_HASH_KEY "/var/lib/dpkg/info/me.aspenuwu.zinnia.list"
#define GOOD_FILENAME_HASH 0x2B0A8D291612FF5C
/// The hash of the path of "incorrect" dpkg .list #1
/// This define will be automatically generated by the preprocessor, only edit the pragma statement!
#pragma blake3 SECTION_FILENAME_HASH_KEY "/var/lib/dpkg/info/org.mr.zinnia.list"
#define BAD_FILENAME_HASH_1 0x3BED67228DFF3D18
/// The hash of the path of "incorrect" dpkg .list #2
/// This define will be automatically generated by the preprocessor, only edit the pragma statement!
#pragma blake3 SECTION_FILENAME_HASH_KEY "/var/lib/dpkg/info/ru.rejail.zinnia.list"
#define BAD_FILENAME_HASH_2 0x46D074833841B84C
/// The hash of the path of "incorrect" dpkg .list #3.
/// This define will be automatically generated by the preprocessor, only edit the pragma statement!
#pragma blake3 SECTION_FILENAME_HASH_KEY "/var/lib/dpkg/info/org.hackyouriphone.zinnia.list"
#define BAD_FILENAME_HASH_3 0xAD48FD7111AA9E45
