[package]
name = "venusflytrap"
version = "0.1.0"
authors = ["aspen <aspenuwu@protonmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
#futures = "0.3.14"
obfstr = "0.3.0"
reqwest = { version = "0.11.2", default-features = false, features = ["rustls-tls", "json"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
tokio = { version = "1.4.0", features = ["full"] }
uuid = { version = "0.8.2", default-features = false, features = ["v4", "serde"] }
